CREATE DATABASE TEMPLATE;


CREATE TABLE USUARIO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	CREATION_USER VARCHAR(255) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	MODIFIED_USER VARCHAR(255) NOT NULL,
	MODIFIED_DATE DATETIME NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'A'
);


INSERT INTO USUARIO (NOME, CREATION_USER, CREATION_DATE, MODIFIED_USER, MODIFIED_DATE) VALUES ('Bruno Fernando', 'bfcorrea', getdate(), 'bfcorrea', getdate());


--CREATE TABLE LOGS (
--	ID INT IDENTITY(1,1) PRIMARY KEY,
--	LOG_TYPE INT NOT NULL,
--	STATUS_CODE INT NOT NULL,
--	TRACE_ID VARCHAR(255) NOT NULL,
--	MESSAGE VARCHAR(255) NOT NULL,
--	SOURCE VARCHAR(255) NOT NULL,
--	STACK_TRACE VARCHAR(MAX) NOT NULL,
--	INNER_EXCEPTION VARCHAR(MAX) NULL,
--	LOG_TIME DATETIME NOT NULL
--);

CREATE TABLE LOG (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	LOG_TYPE INT NOT NULL,
	MESSAGE VARCHAR(MAX) NOT NULL,
	LOG_TIME DATETIME NOT NULL
);