CREATE DATABASE TEMPLATE;

CREATE TABLE USUARIO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	CREATION_USER VARCHAR(255) NOT NULL,
	CREATION_DATE DATETIME NOT NULL,
	MODIFIED_USER VARCHAR(255) NOT NULL,
	MODIFIED_DATE DATETIME NOT NULL,
	ACTIVE CHAR(1) DEFAULT 'A'
);

